# Generated by Django 5.0.6 on 2026-09-24 14:47

import django.db.models.deletion
import redloc.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_enforce_contract_token_unique'),
        ('redloc', '0002_seed_dictionaries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=redloc.models._access_token, editable=False, max_length=64, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('first_opened_at', models.DateTimeField(blank=True, null=True)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('send_status', models.CharField(blank=True, choices=[('', '—'), ('success', 'Отправлено'), ('error', 'Ошибка')], max_length=10)),
                ('send_error', models.TextField(blank=True)),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redloc_links', to='core.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ссылка-доступ',
                'verbose_name_plural': 'Ссылки-доступ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='locationrequest',
            name='access_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='redloc.accesslink'),
        ),
    ]
