# Generated by Django 5.0.6 on 2026-09-29 16:03

import django.db.models.deletion
import redloc.models
import redloc.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redloc', '0003_access_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('love_story', 'Love story'), ('album', 'Альбом')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('description_ru', models.TextField(blank=True)),
                ('description_uz', models.TextField(blank=True)),
                ('shot_at', models.DateField(blank=True, null=True, verbose_name='Дата съёмки')),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolios', to='redloc.location')),
            ],
            options={
                'verbose_name': 'Съёмка (портфолио)',
                'verbose_name_plural': 'Съёмки (портфолио)',
                'ordering': ['order', '-shot_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(height_field='height', storage=redloc.storage.redloc_storage, upload_to=redloc.models.portfolio_photo_path, width_field='width')),
                ('thumbnail', models.ImageField(blank=True, storage=redloc.storage.redloc_storage, upload_to=redloc.models.portfolio_thumb_path)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='redloc.portfolio')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('file', models.FileField(blank=True, storage=redloc.storage.redloc_storage, upload_to=redloc.models.portfolio_video_path)),
                ('youtube_url', models.URLField(blank=True)),
                ('poster', models.ImageField(blank=True, storage=redloc.storage.redloc_storage, upload_to=redloc.models.portfolio_poster_path)),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность, сек')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='redloc.portfolio')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
