# Generated by Django 5.0.6 on 2026-09-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redloc', '0004_portfolio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
