# Generated by Django 5.0.6 on 2026-09-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redloc', '0005_remove_favorites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationRequest',
        ),
    ]
