# Generated by Django 5.0.6 on 2026-09-30 16:17

import redloc.models
import redloc.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redloc', '0008_seed_seasons'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_title_ru', models.CharField(blank=True, max_length=120)),
                ('hero_title_uz', models.CharField(blank=True, max_length=120)),
                ('hero_subtitle_ru', models.CharField(blank=True, max_length=300)),
                ('hero_subtitle_uz', models.CharField(blank=True, max_length=300)),
                ('hero_image', models.ImageField(blank=True, storage=redloc.storage.redloc_storage, upload_to=redloc.models.hero_image_path)),
            ],
            options={
                'verbose_name': 'Настройки главной',
                'verbose_name_plural': 'Настройки главной',
            },
        ),
        migrations.RemoveField(
            model_name='location',
            name='collections',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
