# Generated by Django 5.0.6 on 2026-09-30 16:41

from django.db import migrations, models


def remap(apps, schema_editor):
    # Премиум → ТОП, Новинка снимается; Хит остаётся
    Location = apps.get_model("redloc", "Location")
    Location.objects.filter(badge="premium").update(badge="top")
    Location.objects.filter(badge="new").update(badge="")


class Migration(migrations.Migration):

    dependencies = [
        ('redloc', '0009_remove_collections_add_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='badge',
            field=models.CharField(blank=True, choices=[('', '—'), ('top', 'ТОП'), ('hit', 'Хит'), ('off_season', 'Не сезон')], default='', max_length=10),
        ),
        migrations.RunPython(remap, migrations.RunPython.noop),
    ]
