# Generated by Django 5.0.6 on 2026-09-30 16:49

from django.db import migrations, models


def init_order(apps, schema_editor):
    # Стартовый порядок = как было: по просмотрам и дате
    Location = apps.get_model("redloc", "Location")
    for i, loc in enumerate(Location.objects.order_by("-views_count", "-created_at")):
        Location.objects.filter(pk=loc.pk).update(order=i)


class Migration(migrations.Migration):

    dependencies = [
        ('redloc', '0010_badges_top_hit_off_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(init_order, migrations.RunPython.noop),
    ]
