# Generated by Django 5.0.6 on 2026-10-03 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redloc', '0011_location_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
