# Generated by Django 5.0.6 on 2025-12-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advancehistory",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="workers",
            options={"ordering": ["order"]},
        ),
        migrations.AlterField(
            model_name="advancehistory",
            name="date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="client",
            name="is_vip",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="advance",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="event",
            name="amount",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="telegramadvancenotificationlog",
            name="phone",
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="telegramadvancenotificationlog",
            name="sent_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="telegramadvancenotificationlog",
            name="status",
            field=models.CharField(
                choices=[("success", "Успешно"), ("error", "Ошибка")],
                db_index=True,
                default="error",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="telegramcontractlog",
            name="phone",
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="telegramcontractlog",
            name="sent_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="telegramcontractlog",
            name="status",
            field=models.CharField(
                choices=[("success", "Успешно"), ("error", "Ошибка")],
                db_index=True,
                default="error",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workers",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="workers",
            name="order",
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AddIndex(
            model_name="advancehistory",
            index=models.Index(
                fields=["event", "-date"], name="core_advanc_event_i_e91e1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="advancehistory",
            index=models.Index(fields=["-date"], name="core_advanc_date_19f713_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["is_archived", "is_vip"], name="core_client_is_arch_63ad3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["created_at"], name="core_client_created_f91eae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["client", "created_at"], name="core_event_client__0d1f87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["created_at"], name="core_event_created_0bbd2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["amount"], name="core_event_amount_9c7abd_idx"),
        ),
        migrations.AddIndex(
            model_name="phoneclient",
            index=models.Index(
                fields=["client", "phone_number"], name="core_phonec_client__d1f9c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="telegramadvancenotificationlog",
            index=models.Index(
                fields=["event", "-sent_at"], name="core_telegr_event_i_846938_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="telegramadvancenotificationlog",
            index=models.Index(
                fields=["status", "-sent_at"], name="core_telegr_status_329dda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="telegramcontractlog",
            index=models.Index(
                fields=["event", "-sent_at"], name="core_telegr_event_i_5dd8e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="telegramcontractlog",
            index=models.Index(
                fields=["status", "-sent_at"], name="core_telegr_status_41c36a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workers",
            index=models.Index(fields=["order"], name="core_worker_order_e49e90_idx"),
        ),
    ]
