# Generated by Django 5.0.6 on 2025-12-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_advancehistory_options_alter_workers_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerNotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification_time",
                    models.TimeField(
                        help_text="Время отправки уведомлений (например, 09:00)"
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, help_text="Включены ли автоматические уведомления"
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка уведомлений работникам",
                "verbose_name_plural": "Настройки уведомлений работникам",
            },
        ),
    ]
