# Generated by Django 5.0.6 on 2024-11-10 15:59

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_device_restaurant_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
