# Generated by Django 5.0.6 on 2025-12-12 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_workernotificationsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerNotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone",
                    models.CharField(
                        db_index=True,
                        help_text="Номер телефона работника",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("error", "Ошибка")],
                        db_index=True,
                        default="error",
                        help_text="Статус отправки",
                        max_length=20,
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        help_text="Текст ошибки, если отправка не удалась",
                        null=True,
                    ),
                ),
                (
                    "message_text",
                    models.TextField(
                        blank=True, help_text="Текст отправленного сообщения", null=True
                    ),
                ),
                (
                    "telegram_user_id",
                    models.BigIntegerField(
                        blank=True, help_text="ID пользователя в Telegram", null=True
                    ),
                ),
                (
                    "event_date",
                    models.DateField(
                        db_index=True,
                        help_text="Дата мероприятия, о котором отправлено уведомление",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[("today", "Сегодня"), ("tomorrow", "Завтра")],
                        db_index=True,
                        help_text="Тип уведомления: сегодня или завтра",
                        max_length=20,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Время отправки уведомления",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        help_text="Работник, которому отправлено уведомление",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to="core.workers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог уведомления работнику",
                "verbose_name_plural": "Логи уведомлений работникам",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["worker", "-sent_at"],
                        name="core_worker_worker__8e127b_idx",
                    ),
                    models.Index(
                        fields=["status", "-sent_at"],
                        name="core_worker_status_17a6a9_idx",
                    ),
                    models.Index(
                        fields=["event_date", "-sent_at"],
                        name="core_worker_event_d_c80bf1_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "-sent_at"],
                        name="core_worker_notific_b59730_idx",
                    ),
                ],
            },
        ),
    ]
