# Generated by Django 5.0.6 on 2025-12-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_workernotificationlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="order",
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterModelOptions(
            name="service",
            options={"ordering": ["order"]},
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["order"], name="core_service_order_abc123_idx"),
        ),
    ]

