# Generated by Django 5.0.6 on 2024-11-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_service_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="event_service_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
