# Generated by Django 5.0.6 on 2025-12-27 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_service_order"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="service",
            new_name="core_servic_order_eed70d_idx",
            old_name="core_service_order_abc123_idx",
        ),
    ]
