# Generated by Django 5.0.6 on 2024-11-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_device_event_service_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="event_service_date",
            field=models.DateField(blank=True, default="00.00.0000", null=True),
        ),
    ]
