# Generated by Django 5.0.6 on 2026-02-20 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0006_rename_core_service_order_abc123_idx_core_servic_order_eed70d_idx",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="phoneclient",
            options={"ordering": ["id"]},
        ),
    ]
