# Generated by Django 5.0.6 on 2026-08-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_clienthistory_eventhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="contract_token",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
