# Generated by Django 5.0.6 on 2024-11-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_service_is_active_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="computer_numbers",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
