# Generated by Django 5.0.6 on 2026-08-06 18:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_populate_contract_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="contract_token",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
