# Generated by Django 5.0.6 on 2024-11-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_device_workers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="workers",
            field=models.ManyToManyField(
                blank=True, related_name="devices", to="core.workers"
            ),
        ),
    ]
