# Generated by Django 5.0.6 on 2024-11-18 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_delete_user_event_advance_money_event_amount_money"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
