# Generated by Django 5.0.6 on 2024-11-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="workers",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
