# Generated by Django 4.2.16 on 2024-09-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='client',
        ),
        migrations.AddField(
            model_name='sms',
            name='client',
            field=models.ManyToManyField(related_name='sms_client', to='app.client'),
        ),
    ]
