# Generated by Django 4.2.16 on 2024-09-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_sms_client_sms_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='client',
        ),
        migrations.AddField(
            model_name='sms',
            name='clients',
            field=models.ManyToManyField(related_name='sms_clients', to='app.client'),
        ),
    ]
