# Generated by Django 4.2.16 on 2024-09-08 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_sms_status_smsclientstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMSClientStatus',
        ),
    ]
