# Generated by Django 4.2.16 on 2024-09-08 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_smsclientstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSClientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Отправлено'), ('failed', 'Неуспешно')], max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('sms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_statuses', to='app.sms')),
            ],
        ),
    ]
