# Generated by Django 4.2.16 on 2024-09-08 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_smsclientstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMSClientStatus',
        ),
    ]
