# Generated by Django 4.2.16 on 2024-09-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_smsclientstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
    ]
