# Generated by Django 4.2.16 on 2024-09-13 18:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_client_is_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=1000, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
